job build:
  image:
    "nlescjcer/docker_conda_nano:pytorch"
  script: 
    - cd $HOME && git clone --branch devel --single-branch git://github.com/nlesc-nano/swan.git
    # Instal pytorch-geometric dependencies
    - pip install --verbose --no-cache-dir torch-scatter torch-sparse torch-cluster torch-geometric
    # Install packages
    - cd swan && pip install -e .[test]
    - pytest --cov=swan tests -p no:warnings
  tags:
    - nlescjcer
