job build:
  image:
    "nlescjcer/docker_conda_nano:test"
  script:
    - cd $HOME && git clone --branch master --single-branch git://github.com/nlesc-nano/swan.git
    - cd swan && pip install -e .[dev]
  tags:
    - nlescjcer
  only:
    - master
