version: 2

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  version: 3.7

conda:
  environment: environment.yml

build:
  image: latest

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false  
  
